# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaEspecialista.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import csv
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate, QTime, Qt



class Ui_agendarEspecialista(object):
    def setupUi(self, agendarEspecialista):
        agendarEspecialista.setObjectName("agendarEspecialista")
        agendarEspecialista.resize(600, 400)
        agendarEspecialista.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(agendarEspecialista)
        self.centralwidget.setObjectName("centralwidget")
        self.botonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.botonAtras.setGeometry(QtCore.QRect(20, 320, 75, 23))
        self.botonAtras.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.botonAtras.setObjectName("botonAtras")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(150, 0, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        self.comboEspecialidad = QtWidgets.QComboBox(self.centralwidget)
        self.comboEspecialidad.setGeometry(QtCore.QRect(350, 110, 131, 21))
        self.comboEspecialidad.setStyleSheet("")
        self.comboEspecialidad.setEditable(False)
        self.comboEspecialidad.setCurrentText("")
        self.comboEspecialidad.setObjectName("comboEspecialidad")
        self.comboEspecialidad.addItems(["Oncologia", "Rehabilitacion", "Fisioterapia"])
        self.comboEspecialidad.currentIndexChanged.connect(self.actualizarEspecialistas)
        self.comboEspecialista = QtWidgets.QComboBox(self.centralwidget)
        self.comboEspecialista.setGeometry(QtCore.QRect(350, 150, 131, 21))
        self.comboEspecialista.setStyleSheet("")
        self.comboEspecialista.setEditable(False)
        self.comboEspecialista.setCurrentText("")
        self.comboEspecialista.setObjectName("comboEspecialista")
        self.botonAgendar = QtWidgets.QPushButton(self.centralwidget)
        self.botonAgendar.setGeometry(QtCore.QRect(280, 310, 75, 23))
        self.botonAgendar.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.botonAgendar.setObjectName("botonAgendar")
        self.botonAgendar.clicked.connect(self.agendar)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 190, 61, 21))
        self.label_3.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 150, 61, 21))
        self.label_4.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 110, 61, 21))
        self.label_5.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.label_5.setObjectName("label_5")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(350, 190, 131, 21))
        self.dateEdit.setObjectName("dateEdit")
        fecha_actual = QDate.currentDate()
        self.dateEdit.setMinimumDate(fecha_actual)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 230, 61, 21))
        self.label_6.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.label_6.setObjectName("label_6")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(350, 230, 131, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit.setMinimumTime(QTime(9, 0)) 
        self.timeEdit.setMaximumTime(QTime(18, 0))
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 270, 61, 21))
        self.label_7.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.label_7.setObjectName("label_7")
        self.comboSala = QtWidgets.QComboBox(self.centralwidget)
        self.comboSala.setGeometry(QtCore.QRect(350, 270, 131, 21))
        self.comboSala.setStyleSheet("")
        self.comboSala.setEditable(False)
        self.comboSala.setCurrentText("")
        self.comboSala.setObjectName("comboSala")
        self.comboSala.addItems(["Sala 1", "Sala 2", "Sala 3"])
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(160, 70, 61, 21))
        self.label_8.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.label_8.setObjectName("label_8")
        self.lineNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineNombre.setGeometry(QtCore.QRect(350, 70, 131, 20))
        self.lineNombre.setObjectName("lineNombre")
        agendarEspecialista.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(agendarEspecialista)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        agendarEspecialista.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(agendarEspecialista)
        self.statusbar.setObjectName("statusbar")
        agendarEspecialista.setStatusBar(self.statusbar)

        self.retranslateUi(agendarEspecialista)
        QtCore.QMetaObject.connectSlotsByName(agendarEspecialista)

    def retranslateUi(self, agendarEspecialista):
        _translate = QtCore.QCoreApplication.translate
        agendarEspecialista.setWindowTitle(_translate("agendarEspecialista", "MainWindow"))
        self.botonAtras.setText(_translate("agendarEspecialista", "Atras"))
        self.titulo.setText(_translate("agendarEspecialista", "<html><head/><body><p>Agendar hora especialista</p></body></html>"))
        self.botonAgendar.setText(_translate("agendarEspecialista", "Agendar Hora"))
        self.label_3.setText(_translate("agendarEspecialista", "Fecha"))
        self.label_4.setText(_translate("agendarEspecialista", "Especialista"))
        self.label_5.setText(_translate("agendarEspecialista", "Especialidad"))
        self.label_6.setText(_translate("agendarEspecialista", "Hora"))
        self.label_7.setText(_translate("agendarEspecialista", "Sala"))
        self.label_8.setText(_translate("agendarEspecialista", "Nombre"))
    
    def actualizarEspecialistas(self):
        especialidad = self.comboEspecialidad.currentText()
        self.comboEspecialista.clear()
        if especialidad == "Oncologia":
            self.comboEspecialista.addItems(["Mario Olea", "Rodrigo Nuñez"])
        elif especialidad == "Rehabilitacion":
            self.comboEspecialista.addItems(["Benjamin Olea", "Fernanda Morales"])
        elif especialidad == "Fisioterapia":
            self.comboEspecialista.addItems(["Damaris Rojas"])

    def agendar(self):
        especialidad = self.comboEspecialidad.currentText()
        especialista = self.comboEspecialista.currentText()
        fecha = self.dateEdit.date().toString(Qt.ISODate)
        hora = self.timeEdit.time().toString()
        sala = self.comboSala.currentText()
        nombre = self.lineNombre.text()

        archivo_existe = os.path.exists("Citas.csv")
        
        with open("Citas.csv", 'a', newline='') as file:
            writer = csv.writer(file)
            if not archivo_existe:
                writer.writerow(["fecha", "nombre", "especialista", "especialidad", "hora", "sala"])
            
            writer.writerow([fecha, nombre, especialista, especialidad, hora, sala])
            print("se ha agendado correctamente")