# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urgencias.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import csv


class Ui_agendarUrgencias(object):
    def setupUi(self, agendarUrgencias):
        agendarUrgencias.setObjectName("agendarUrgencias")
        agendarUrgencias.resize(500, 402)
        self.centralwidget = QtWidgets.QWidget(agendarUrgencias)
        self.centralwidget.setObjectName("centralwidget")
        self.lineNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineNombre.setGeometry(QtCore.QRect(130, 70, 113, 20))
        self.lineNombre.setObjectName("lineNombre")
        self.lineContacto = QtWidgets.QLineEdit(self.centralwidget)
        self.lineContacto.setGeometry(QtCore.QRect(130, 150, 113, 20))
        self.lineContacto.setObjectName("lineContacto")
        self.lineDireccion = QtWidgets.QLineEdit(self.centralwidget)
        self.lineDireccion.setGeometry(QtCore.QRect(130, 190, 113, 20))
        self.lineDireccion.setObjectName("lineDireccion")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.label.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 61, 21))
        self.label_2.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 61, 21))
        self.label_3.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 61, 21))
        self.label_4.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.label_4.setObjectName("label_4")
        self.comboGravedad = QtWidgets.QComboBox(self.centralwidget)
        self.comboGravedad.setGeometry(QtCore.QRect(130, 30, 111, 22))
        self.comboGravedad.setObjectName("comboGravedad")
        self.comboGravedad.addItems(["1", "2", "3", "4", "5"])
        self.botonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.botonAtras.setGeometry(QtCore.QRect(30, 330, 75, 23))
        self.botonAtras.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.botonAtras.setObjectName("botonAtras")
        self.botonAtras.clicked.connect(agendarUrgencias.close)
        self.botonGuardar = QtWidgets.QPushButton(self.centralwidget)
        self.botonGuardar.setGeometry(QtCore.QRect(190, 280, 111, 23))
        self.botonGuardar.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.botonGuardar.setObjectName("botonGuardar")
        self.botonGuardar.clicked.connect(self.agendar)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 61, 21))
        self.label_5.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.label_5.setObjectName("label_5")
        self.lineDueno = QtWidgets.QLineEdit(self.centralwidget)
        self.lineDueno.setGeometry(QtCore.QRect(130, 110, 113, 20))
        self.lineDueno.setObjectName("lineDueno")
        self.lineDueno.raise_()
        self.lineNombre.raise_()
        self.lineContacto.raise_()
        self.lineDireccion.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.comboGravedad.raise_()
        self.botonAtras.raise_()
        self.botonGuardar.raise_()
        self.label_5.raise_()
        agendarUrgencias.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(agendarUrgencias)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        agendarUrgencias.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(agendarUrgencias)
        self.statusbar.setObjectName("statusbar")
        agendarUrgencias.setStatusBar(self.statusbar)

        self.retranslateUi(agendarUrgencias)
        QtCore.QMetaObject.connectSlotsByName(agendarUrgencias)

    def retranslateUi(self, agendarUrgencias):
        _translate = QtCore.QCoreApplication.translate
        agendarUrgencias.setWindowTitle(_translate("agendarUrgencias", "MainWindow"))
        self.label.setText(_translate("agendarUrgencias", "Gravedad"))
        self.label_2.setText(_translate("agendarUrgencias", "Nombre"))
        self.label_3.setText(_translate("agendarUrgencias", "Contacto"))
        self.label_4.setText(_translate("agendarUrgencias", "Direccion"))
        self.botonAtras.setText(_translate("agendarUrgencias", "Atras"))
        self.botonGuardar.setText(_translate("agendarUrgencias", "Guardar Registro"))
        self.label_5.setText(_translate("agendarUrgencias", "Dueño"))

    def agendar(self):
        direccion = self.lineDireccion.text()
        contacto = self.lineContacto.text()
        gravedad = self.comboGravedad.currentText()   
        nombre = self.lineNombre.text()
        dueno = self.lineDueno.text()
        
        archivo_existe = os.path.exists("Quirofano.csv")
        
        with open("Urgencias.csv", 'a', newline='') as file:
            writer = csv.writer(file)
            if not archivo_existe:
                writer.writerow(["nombre","dueno","gravedad", "contacto", "direccion"])
            
            writer.writerow([nombre, dueno, gravedad, contacto, direccion])