# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ADMINISTRACION.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class uiAdmin(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 410)
        MainWindow.setMinimumSize(QtCore.QSize(602, 410))
        MainWindow.setMaximumSize(QtCore.QSize(602, 410))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 81))
        self.label.setStyleSheet("background-color: rgb(79, 163, 166);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 30, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_2.setStyleSheet("background-color: rgb(79, 163, 166);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 80, 701, 411))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(150, -30, 291, 371))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(
            "imagenes\Logo-removebg-preview.png"))
        self.label_3.setObjectName("label_3")
        self.AGREGARUSUARIO = QtWidgets.QPushButton(self.frame)
        self.AGREGARUSUARIO.setGeometry(QtCore.QRect(30, 110, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.AGREGARUSUARIO.setFont(font)
        self.AGREGARUSUARIO.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AGREGARUSUARIO.setStyleSheet("background-color: rgb(79, 163, 166);\n"
                                           "border-radius: 5px;")
        self.AGREGARUSUARIO.setObjectName("AGREGARUSUARIO")
        self.BUSCARUSUARIO = QtWidgets.QPushButton(self.frame)
        self.BUSCARUSUARIO.setGeometry(QtCore.QRect(390, 110, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.BUSCARUSUARIO.setFont(font)
        self.BUSCARUSUARIO.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BUSCARUSUARIO.setStyleSheet("background-color: rgb(79, 163, 166);\n"
                                          "border-radius: 5px;")
        self.BUSCARUSUARIO.setObjectName("BUSCARUSUARIO")
        self.frame.raise_()
        self.label.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Clinica CVI"))
        self.label_2.setText(_translate("MainWindow", "Administracion"))
        self.AGREGARUSUARIO.setText(
            _translate("MainWindow", "Agregar usuario"))
        self.BUSCARUSUARIO.setText(
            _translate("MainWindow", "Buscar usuario"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = uiAdmin()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
