# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegistroUrgencias.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(697, 509)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(697, 509))
        mainWindow.setMaximumSize(QtCore.QSize(697, 509))
        mainWindow.setStyleSheet("alternate-background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 711, 511))
        self.frame.setMinimumSize(QtCore.QSize(711, 511))
        self.frame.setMaximumSize(QtCore.QSize(711, 511))
        self.frame.setSizeIncrement(QtCore.QSize(10000, 10000))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(-10, -20, 721, 101))
        self.frame_2.setStyleSheet("background-color: rgb(79, 163, 166);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(50, 80, 120, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(70, 99, 331, 51))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.titulo = QtWidgets.QLabel(self.frame_2)
        self.titulo.setGeometry(QtCore.QRect(186, 30, 400, 60))
        font = QtGui.QFont()
        font.setFamily("Chewy")
        font.setPointSize(36)
        self.titulo.setFont(font)
        self.titulo.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.titulo.setObjectName("titulo")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 61, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("imagenes/Atras.png"))
        self.label_3.setObjectName("label_3")
        self.btnAtras = QtWidgets.QPushButton(self.frame_2)
        self.btnAtras.setGeometry(QtCore.QRect(40, 36, 50, 50))
        self.btnAtras.setStyleSheet("\n"
"\n"
"\n"
"QPushButton {\n"
"  \n"
"    \n"
"    border-radius: 20px;\n"
"\n"
"  \n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: #74b6b6;\n"
"}\n"
"")
        self.btnAtras.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagenes/boton_regresar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAtras.setIcon(icon)
        self.btnAtras.setIconSize(QtCore.QSize(50, 50))
        self.btnAtras.setObjectName("btnAtras")
        self.label_logo = QtWidgets.QLabel(self.frame)
        self.label_logo.setGeometry(QtCore.QRect(420, 120, 291, 301))
        font = QtGui.QFont()
        font.setFamily("Chewy")
        font.setPointSize(16)
        self.label_logo.setFont(font)
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("imagenes/Logo-removebg-preview.png"))
        self.label_logo.setObjectName("label_logo")
        self.listaUrgencias = QtWidgets.QTableWidget(self.frame)
        self.listaUrgencias.setGeometry(QtCore.QRect(20, 100, 502, 318))
        self.listaUrgencias.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listaUrgencias.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listaUrgencias.setObjectName("listaUrgencias")
        self.listaUrgencias.setColumnCount(5)
        self.listaUrgencias.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.listaUrgencias.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.listaUrgencias.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.listaUrgencias.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.listaUrgencias.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.listaUrgencias.setHorizontalHeaderItem(4, item)
        self.listaUrgencias.horizontalHeader().setDefaultSectionSize(100)
        self.listaUrgencias.horizontalHeader().setMinimumSectionSize(39)
        self.listaUrgencias.verticalHeader().setVisible(False)
        self.labelN = QtWidgets.QLabel(self.frame)
        self.labelN.setGeometry(QtCore.QRect(20, 460, 176, 31))
        font = QtGui.QFont()
        font.setFamily("Chewy")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.labelN.setFont(font)
        self.labelN.setStyleSheet("")
        self.labelN.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelN.setObjectName("labelN")
        self.buscarNombre = QtWidgets.QLineEdit(self.frame)
        self.buscarNombre.setGeometry(QtCore.QRect(199, 460, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buscarNombre.setFont(font)
        self.buscarNombre.setMaxLength(876453242)
        self.buscarNombre.setObjectName("buscarNombre")
        self.labelF = QtWidgets.QLabel(self.frame)
        self.labelF.setGeometry(QtCore.QRect(20, 430, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Chewy")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.labelF.setFont(font)
        self.labelF.setStyleSheet("")
        self.labelF.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelF.setObjectName("labelF")
        self.fechaFiltro = QtWidgets.QDateEdit(self.centralwidget)
        self.fechaFiltro.setGeometry(QtCore.QRect(64, 435, 110, 22))
        self.fechaFiltro.setMaximumDate(QtCore.QDate(2024, 12, 31))
        self.fechaFiltro.setMinimumDate(QtCore.QDate(2023, 6, 13))
        self.fechaFiltro.setCalendarPopup(True)
        self.fechaFiltro.setObjectName("fechaFiltro")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Clinica CVI"))
        self.titulo.setText(_translate("mainWindow", "Registro Urgencias"))
        item = self.listaUrgencias.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Mascota"))
        item = self.listaUrgencias.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Dueño"))
        item = self.listaUrgencias.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Gravedad"))
        item = self.listaUrgencias.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Fecha"))
        item = self.listaUrgencias.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Ambulancia"))
        self.labelN.setText(_translate("mainWindow", "Buscar Nombre Mascota:"))
        self.labelF.setText(_translate("mainWindow", "Fecha:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
