# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ingresar_mascota.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QtGui.QIcon('Imagenes/logo.png'))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 540)
        MainWindow.setMinimumSize(QtCore.QSize(709, 540))
        MainWindow.setMaximumSize(QtCore.QSize(709, 540))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 741, 540))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 731, 541))
        self.label.setMinimumSize(QtCore.QSize(731, 541))
        self.label.setMaximumSize(QtCore.QSize(731, 541))
        self.label.setStyleSheet("background: #FFFFFF;")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 731, 80))
        font = QtGui.QFont()
        font.setFamily("Chewy")
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("background: #4fa3a6;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(210, 140, 291, 281))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("imagenes/Logo-removebg-preview.png"))
        self.label_3.setObjectName("label_3")
        self.Lista_reservas = QtWidgets.QPushButton(self.widget)
        self.Lista_reservas.setGeometry(QtCore.QRect(50, 150, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Chewy")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Lista_reservas.setFont(font)
        self.Lista_reservas.setStyleSheet("QPushButton {\n"
"    background: #4fa3a6;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: #74b6b6;\n"
"}\n"
"")
        self.Lista_reservas.setObjectName("Lista_reservas")
        self.control_rutinario = QtWidgets.QPushButton(self.widget)
        self.control_rutinario.setGeometry(QtCore.QRect(50, 330, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Chewy")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.control_rutinario.setFont(font)
        self.control_rutinario.setStyleSheet("QPushButton {\n"
"    background: #4fa3a6;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: #74b6b6;\n"
"}\n"
"")
        self.control_rutinario.setObjectName("control_rutinario")
        self.botonAtras = QtWidgets.QPushButton(self.widget)
        self.botonAtras.setGeometry(QtCore.QRect(20, 15, 50, 50))
        self.botonAtras.setStyleSheet("\n"
"\n"
"\n"
"QPushButton {\n"
"  \n"
"    \n"
"    border-radius: 20px;\n"
"\n"
"  \n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: #74b6b6;\n"
"}\n"
"")
        self.botonAtras.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagenes/boton_regresar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonAtras.setIcon(icon)
        self.botonAtras.setIconSize(QtCore.QSize(50, 50))
        self.botonAtras.setObjectName("botonAtras")
        self.especialista = QtWidgets.QPushButton(self.widget)
        self.especialista.setGeometry(QtCore.QRect(490, 150, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Chewy")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.especialista.setFont(font)
        self.especialista.setStyleSheet("QPushButton {\n"
"    background: #4fa3a6;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: #74b6b6;\n"
"}\n"
"")
        self.especialista.setObjectName("especialista")
        self.quirofano = QtWidgets.QPushButton(self.widget)
        self.quirofano.setGeometry(QtCore.QRect(490, 330, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Chewy")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.quirofano.setFont(font)
        self.quirofano.setStyleSheet("QPushButton {\n"
"    background: #4fa3a6;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: #74b6b6;\n"
"}\n"
"")
        self.quirofano.setObjectName("quirofano")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Clinica CVI"))
        self.label_2.setText(_translate("MainWindow", "Bienvenido: "))
        self.Lista_reservas.setText(_translate("MainWindow", "Lista de Reservas"))
        self.control_rutinario.setText(_translate("MainWindow", "Control Rutinario"))
        self.especialista.setText(_translate("MainWindow", "Especialista"))
        self.quirofano.setText(_translate("MainWindow", "Quirofano"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
