# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Reserva.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import Resources_rc
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(700, 552)
        MainWindow.setMinimumSize(QtCore.QSize(700, 552))
        MainWindow.setMaximumSize(QtCore.QSize(700, 552))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 711, 540))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Fondo = QtWidgets.QLabel(self.frame)
        self.Fondo.setGeometry(QtCore.QRect(0, 0, 711, 540))
        self.Fondo.setStyleSheet("background: #4fa3a6")
        self.Fondo.setText("")
        self.Fondo.setObjectName("Fondo")
        self.FondoBlanco = QtWidgets.QLabel(self.frame)
        self.FondoBlanco.setGeometry(QtCore.QRect(209, 140, 301, 301))
        self.FondoBlanco.setStyleSheet("background: #ffffff")
        self.FondoBlanco.setText("")
        self.FondoBlanco.setObjectName("FondoBlanco")
        self.ComboBoxCliente = QtWidgets.QComboBox(self.frame)
        self.ComboBoxCliente.setGeometry(QtCore.QRect(260, 270, 201, 41))
        self.ComboBoxCliente.setStyleSheet("border: 3px solid #4fa3a6 ;")
        self.ComboBoxCliente.setObjectName("ComboBoxCliente")
        self.ComboBoxCliente.addItem("")
        self.imagenUsuario = QtWidgets.QLabel(self.frame)
        self.imagenUsuario.setGeometry(QtCore.QRect(293, 140, 131, 91))
        self.imagenUsuario.setStyleSheet("border-image:url(:/Images/usuario.png);")
        self.imagenUsuario.setText("")
        self.imagenUsuario.setObjectName("imagenUsuario")
        self.ButtonIngresar = QtWidgets.QPushButton(self.frame)
        self.ButtonIngresar.setGeometry(QtCore.QRect(300, 330, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonIngresar.setFont(font)
        self.ButtonIngresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ButtonIngresar.setStyleSheet("QPushButton{\n"
"    border-radius: 13px;\n"
"    background-color: rgb(211, 211, 211);\n"
"}\n"
"QPushButton::hover {\n"
"    background: #4fa3a6 ;\n"
"}")
        self.ButtonIngresar.setObjectName("ButtonIngresar")
        self.ButtonUrgencia = QtWidgets.QPushButton(self.frame)
        self.ButtonUrgencia.setGeometry(QtCore.QRect(300, 380, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonUrgencia.setFont(font)
        self.ButtonUrgencia.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ButtonUrgencia.setStyleSheet("QPushButton{\n"
"    border-radius: 13px;\n"
"    background-color: rgb(211, 211, 211);\n"
"}\n"
"QPushButton::hover {\n"
"    background: red ;\n"
"}")
        self.ButtonUrgencia.setObjectName("ButtonUrgencia")
        self.Titulo = QtWidgets.QLabel(self.frame)
        self.Titulo.setGeometry(QtCore.QRect(100, 30, 521, 61))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(60)
        font.setBold(False)
        font.setWeight(50)
        self.Titulo.setFont(font)
        self.Titulo.setStyleSheet("color:white")
        self.Titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.Titulo.setObjectName("Titulo")
        self.FotoPerrito = QtWidgets.QLabel(self.frame)
        self.FotoPerrito.setGeometry(QtCore.QRect(290, 0, 141, 131))
        self.FotoPerrito.setStyleSheet("border-image:url(:/Images/Logo-removebg-preview.png);")
        self.FotoPerrito.setText("")
        self.FotoPerrito.setObjectName("FotoPerrito")
        self.ButtonAtras = QtWidgets.QPushButton(self.frame)
        self.ButtonAtras.setGeometry(QtCore.QRect(20, 20, 50, 50))
        self.ButtonAtras.setStyleSheet("\n"
"\n"
"\n"
"QPushButton {\n"
"  \n"
"    \n"
"    border-radius: 20px;\n"
"\n"
"  \n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: #74b6b6;\n"
"}\n"
"")
        self.ButtonAtras.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagenes/boton_regresar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonAtras.setIcon(icon)
        self.ButtonAtras.setIconSize(QtCore.QSize(50, 50))
        self.ButtonAtras.setObjectName("ButtonAtras")
        self.Fondo.raise_()
        self.FondoBlanco.raise_()
        self.ComboBoxCliente.raise_()
        self.imagenUsuario.raise_()
        self.ButtonIngresar.raise_()
        self.ButtonUrgencia.raise_()
        self.FotoPerrito.raise_()
        self.Titulo.raise_()
        self.ButtonAtras.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Clinica CVI"))
        self.ComboBoxCliente.setItemText(0, _translate("MainWindow", "Elegir Cliente"))
        self.ButtonIngresar.setText(_translate("MainWindow", "Ingresar"))
        self.ButtonUrgencia.setText(_translate("MainWindow", "Urgencia"))
        self.Titulo.setText(_translate("MainWindow", "Reservas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
