# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urgencia.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import recurso_elias


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 741, 540))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 731, 541))
        self.label.setStyleSheet("background: #FFFFFF;")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 731, 80))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(41)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("background: #4fa3a6;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(390, 110, 301, 271))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-image: url(:/image/perro.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background: #4fa3a6;\n"
"border-radius: 10;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.Nombre_mascota = QtWidgets.QLineEdit(self.widget)
        self.Nombre_mascota.setGeometry(QtCore.QRect(40, 210, 131, 21))
        self.Nombre_mascota.setStyleSheet("border: 2px solid #4fa3a6 ;\n"
"")
        self.Nombre_mascota.setObjectName("Nombre_mascota")
        self.Dueno_edit = QtWidgets.QLineEdit(self.widget)
        self.Dueno_edit.setGeometry(QtCore.QRect(190, 210, 113, 21))
        self.Dueno_edit.setStyleSheet("border: 2px solid #4fa3a6 ;")
        self.Dueno_edit.setObjectName("Dueno_edit")
        self.telefono_edit = QtWidgets.QLineEdit(self.widget)
        self.telefono_edit.setGeometry(QtCore.QRect(40, 270, 131, 21))
        self.telefono_edit.setStyleSheet("border: 2px solid #4fa3a6 ;")
        self.telefono_edit.setObjectName("telefono_edit")
        self.domicilio_edit = QtWidgets.QLineEdit(self.widget)
        self.domicilio_edit.setGeometry(QtCore.QRect(190, 270, 113, 21))
        self.domicilio_edit.setStyleSheet("border: 2px solid #4fa3a6 ;")
        self.domicilio_edit.setObjectName("domicilio_edit")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(40, 190, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(190, 190, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(40, 250, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(190, 250, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.Gravedad_box = QtWidgets.QComboBox(self.widget)
        self.Gravedad_box.setGeometry(QtCore.QRect(40, 330, 131, 22))
        self.Gravedad_box.setStyleSheet("border: 2px solid #4fa3a6 ;")
        self.Gravedad_box.setObjectName("Gravedad_box")
        self.Gravedad_box.addItem("")
        self.Gravedad_box.addItem("")
        self.Gravedad_box.addItem("")
        self.Gravedad_box.addItem("")
        self.Gravedad_box.addItem("")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(40, 310, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Ver_registro = QtWidgets.QPushButton(self.widget)
        self.Ver_registro.setGeometry(QtCore.QRect(420, 390, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Ver_registro.setFont(font)
        self.Ver_registro.setStyleSheet("QPushButton {\n"
"    background: #4fa3a6;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: #74b6b6;\n"
"}\n"
"")
        self.Ver_registro.setObjectName("Ver_registro")
        self.Guardar_registro = QtWidgets.QPushButton(self.widget)
        self.Guardar_registro.setGeometry(QtCore.QRect(420, 450, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Guardar_registro.setFont(font)
        self.Guardar_registro.setStyleSheet("QPushButton {\n"
"    background: #4fa3a6;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: #74b6b6;\n"
"}\n"
"")
        self.Guardar_registro.setObjectName("Guardar_registro")
        self.botonAtras = QtWidgets.QPushButton(self.widget)
        self.botonAtras.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.botonAtras.setStyleSheet("\n"
"\n"
"\n"
"QPushButton {\n"
"  \n"
"    \n"
"    border-radius: 20px;\n"
"\n"
"  \n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: #74b6b6;\n"
"}\n"
"")
        self.botonAtras.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/Atras.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonAtras.setIcon(icon)
        self.botonAtras.setIconSize(QtCore.QSize(71, 61))
        self.botonAtras.setObjectName("botonAtras")
        self.AmbulanciacheckBox = QtWidgets.QCheckBox(self.widget)
        self.AmbulanciacheckBox.setGeometry(QtCore.QRect(190, 320, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setBold(True)
        font.setWeight(75)
        self.AmbulanciacheckBox.setFont(font)
        self.AmbulanciacheckBox.setStyleSheet("\n"
"")
        self.AmbulanciacheckBox.setObjectName("checkBox")
        self.AmbulanciacheckBox.setDisabled(True)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Urgencia"))
        self.label_4.setText(_translate("MainWindow", "Datos de la consulta"))
        self.label_5.setText(_translate("MainWindow", "Nombre de la mascota"))
        self.label_6.setText(_translate("MainWindow", "Dueño"))
        self.label_7.setText(_translate("MainWindow", "Telefono"))
        self.label_8.setText(_translate("MainWindow", "Domicilio"))
        self.Gravedad_box.setItemText(0, _translate("MainWindow", "1"))
        self.Gravedad_box.setItemText(1, _translate("MainWindow", "2"))
        self.Gravedad_box.setItemText(2, _translate("MainWindow", "3"))
        self.Gravedad_box.setItemText(3, _translate("MainWindow", "4"))
        self.Gravedad_box.setItemText(4, _translate("MainWindow", "5"))
        self.label_9.setText(_translate("MainWindow", "Gravedad"))
        self.Ver_registro.setText(_translate("MainWindow", "Ver Registro Urgencias"))
        self.Guardar_registro.setText(_translate("MainWindow", "Guardar Registro"))
        self.AmbulanciacheckBox.setText(_translate("MainWindow", "Ambulancia"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
