# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaMenuEspecialista.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from AgendarEspecialista import Ui_agendarEspecialista
from PyQt5 import QtCore, QtGui, QtWidgets
from verHorasEspecialista import Ui_horasEspecialista

class VentanaEspecialistaMenu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.botonAgendar = QtWidgets.QPushButton(self.centralwidget)
        self.botonAgendar.setGeometry(QtCore.QRect(160, 150, 71, 61))
        self.botonAgendar.setObjectName("botonAgendar")
        self.botonAgendar.clicked.connect(self.abrirVentAgendar)
        self.botonVerHoras = QtWidgets.QPushButton(self.centralwidget)
        self.botonVerHoras.setGeometry(QtCore.QRect(330, 150, 71, 61))
        self.botonVerHoras.setObjectName("botonVerHoras")
        self.botonVerHoras.clicked.connect(self.abrirVentVerHoras)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 10, 231, 71))
        self.label.setObjectName("label")
        self.botonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.botonAtras.setGeometry(QtCore.QRect(20, 300, 75, 23))
        self.botonAtras.setObjectName("botonAtras")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botonAgendar.setText(_translate("MainWindow", "Agendar"))
        self.botonVerHoras.setText(_translate("MainWindow", "Ver Horas"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Menu especialistas</span></p></body></html>"))
        self.botonAtras.setText(_translate("MainWindow", "Atras"))
        
    def abrirVentAgendar(self):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = Ui_agendarEspecialista()
        self.ui.setupUi(self.ventana)
        self.ventana.show()
    
    def abrirVentVerHoras(self):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = Ui_horasEspecialista()
        self.ui.setupUi(self.ventana)
        self.ventana.show()   
