# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaMenuUrgencias.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from registrarUrgencia import Ui_agendarUrgencias
from verUrgencias import Ui_horasUrgencias

class Ui_VentanaMenuUrgencias(object):
    def setupUi(self, VentanaMenuUrgencias):
        VentanaMenuUrgencias.setObjectName("VentanaMenuUrgencias")
        VentanaMenuUrgencias.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(VentanaMenuUrgencias)
        self.centralwidget.setObjectName("centralwidget")
        self.botonRegistrar = QtWidgets.QPushButton(self.centralwidget)
        self.botonRegistrar.setGeometry(QtCore.QRect(160, 150, 81, 61))
        self.botonRegistrar.setObjectName("botonRegistrar")
        self.botonRegistrar.clicked.connect(self.abrirVentRegistrar)
        self.botonVerHoras = QtWidgets.QPushButton(self.centralwidget)
        self.botonVerHoras.setGeometry(QtCore.QRect(330, 150, 81, 61))
        self.botonVerHoras.setObjectName("botonVerHoras")
        self.botonVerHoras.clicked.connect(self.abrirVentRegistros)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 30, 231, 71))
        self.label.setObjectName("label")
        self.botonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.botonAtras.setGeometry(QtCore.QRect(20, 300, 75, 23))
        self.botonAtras.setObjectName("botonAtras")
        self.botonAtras.clicked.connect(VentanaMenuUrgencias.close)
        VentanaMenuUrgencias.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaMenuUrgencias)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        VentanaMenuUrgencias.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaMenuUrgencias)
        self.statusbar.setObjectName("statusbar")
        VentanaMenuUrgencias.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaMenuUrgencias)
        QtCore.QMetaObject.connectSlotsByName(VentanaMenuUrgencias)

    def retranslateUi(self, VentanaMenuUrgencias):
        _translate = QtCore.QCoreApplication.translate
        VentanaMenuUrgencias.setWindowTitle(_translate("VentanaMenuUrgencias", "MainWindow"))
        self.botonRegistrar.setText(_translate("VentanaMenuUrgencias", "Registrar"))
        self.botonVerHoras.setText(_translate("VentanaMenuUrgencias", "Ver Registros"))
        self.label.setText(_translate("VentanaMenuUrgencias", "<html><head/><body><p><span style=\" font-size:20pt;\">Menu urgencias</span></p><p><br/></p></body></html>"))
        self.botonAtras.setText(_translate("VentanaMenuUrgencias", "Atras"))

    def abrirVentRegistrar(self):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = Ui_agendarUrgencias()
        self.ui.setupUi(self.ventana)
        self.ventana.show()

    def abrirVentRegistros(self):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = Ui_horasUrgencias()
        self.ui.setupUi(self.ventana)
        self.ventana.show()