# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaMenuControles.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from AgendarControl import Ui_agendarControl
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from verHorasControles import Ui_horasControles


class Ui_VentanaMenuControles(object):
    def setupUi(self, VentanaMenuControles):
        VentanaMenuControles.setObjectName("VentanaMenuControles")
        VentanaMenuControles.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(VentanaMenuControles)
        self.centralwidget.setObjectName("centralwidget")
        self.botonAgendar = QtWidgets.QPushButton(self.centralwidget)
        self.botonAgendar.setGeometry(QtCore.QRect(160, 150, 81, 61))
        self.botonAgendar.setObjectName("botonAgendar")
        self.botonAgendar.clicked.connect(self.abrirVentAgendar)
        self.botonVerHoras = QtWidgets.QPushButton(self.centralwidget)
        self.botonVerHoras.setGeometry(QtCore.QRect(330, 150, 81, 61))
        self.botonVerHoras.setObjectName("botonVerHoras")
        self.botonVerHoras.clicked.connect(self.abrirVentVerHoras)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 30, 231, 71))
        self.label.setObjectName("label")
        self.botonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.botonAtras.setGeometry(QtCore.QRect(20, 300, 75, 23))
        self.botonAtras.setObjectName("botonAtras")
        VentanaMenuControles.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaMenuControles)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        VentanaMenuControles.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaMenuControles)
        self.statusbar.setObjectName("statusbar")
        VentanaMenuControles.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaMenuControles)
        QtCore.QMetaObject.connectSlotsByName(VentanaMenuControles)

    def retranslateUi(self, VentanaMenuControles):
        _translate = QtCore.QCoreApplication.translate
        VentanaMenuControles.setWindowTitle(_translate("VentanaMenuControles", "MainWindow"))
        self.botonAgendar.setText(_translate("VentanaMenuControles", "Agendar"))
        self.botonVerHoras.setText(_translate("VentanaMenuControles", "Ver horas"))
        self.label.setText(_translate("VentanaMenuControles", "<html><head/><body><p><span style=\" font-size:20pt;\">Menu controles</span></p><p><br/></p></body></html>"))
        self.botonAtras.setText(_translate("VentanaMenuControles", "Atras"))
    
    def abrirVentAgendar(self):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = Ui_agendarControl()
        self.ui.setupUi(self.ventana)
        self.ventana.show()
    
    def abrirVentVerHoras(self):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = Ui_horasControles()
        self.ui.setupUi(self.ventana)
        self.ventana.show()
    