# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaAdministracion.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from IngresarUsuario import Ui_ventIngresarUsuario
from VentVerUsuario import Ui_VentVerUsuario

class Ui_VentAdminUsuario(object):
    def setupUi(self, VentAdminUsuario):
        VentAdminUsuario.setObjectName("VentAdminUsuario")
        VentAdminUsuario.resize(797, 527)
        VentAdminUsuario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnAgregarUsuario = QtWidgets.QPushButton(VentAdminUsuario)
        self.btnAgregarUsuario.setGeometry(QtCore.QRect(130, 210, 191, 61))
        self.btnAgregarUsuario.setStyleSheet("background-color: rgb(79, 163, 166);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(0, 51, 102);\n"
"border-radius: 5px;")
        self.btnAgregarUsuario.setObjectName("btnAgregarUsuario")
        self.btnAgregarUsuario.clicked.connect(lambda: self.cambiarVent(Ui_ventIngresarUsuario))
        self.btnVerUsuario = QtWidgets.QPushButton(VentAdminUsuario)
        self.btnVerUsuario.setGeometry(QtCore.QRect(450, 210, 191, 61))
        self.btnVerUsuario.setStyleSheet("background-color: rgb(79, 163, 166);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(0, 51, 102);\n"
"border-radius: 5px;")
        self.btnVerUsuario.setObjectName("btnVerUsuario")
        self.btnVerUsuario.clicked.connect(lambda: self.cambiarVent(Ui_VentVerUsuario))
        self.label = QtWidgets.QLabel(VentAdminUsuario)
        self.label.setGeometry(QtCore.QRect(0, 0, 797, 130))
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imagenes/bannerAdmin.png"))
        self.label.setObjectName("label")
        self.btnRegresar = QtWidgets.QPushButton(VentAdminUsuario)
        self.btnRegresar.setGeometry(QtCore.QRect(20, 50, 31, 31))
        self.btnRegresar.setStyleSheet("background-color: transparent;")
        self.btnRegresar.setText("")
        self.btnRegresar.setObjectName("btnRegresar")
        self.btnRegresar.clicked.connect(VentAdminUsuario.close)
        self.label_2 = QtWidgets.QLabel(VentAdminUsuario)
        self.label_2.setGeometry(QtCore.QRect(240, 140, 281, 311))
        self.label_2.setStyleSheet("background-color: transparent;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("imagenes/Logo-removebg-preview.png"))
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.btnAgregarUsuario.raise_()
        self.btnVerUsuario.raise_()
        self.label.raise_()
        self.btnRegresar.raise_()

        self.retranslateUi(VentAdminUsuario)
        QtCore.QMetaObject.connectSlotsByName(VentAdminUsuario)

    def retranslateUi(self, VentAdminUsuario):
        _translate = QtCore.QCoreApplication.translate
        VentAdminUsuario.setWindowTitle(_translate("VentAdminUsuario", "VentAdminUsuario"))
        self.btnAgregarUsuario.setText(_translate("VentAdminUsuario", "Agregar Usuario"))
        self.btnVerUsuario.setText(_translate("VentAdminUsuario", "Ver Usuario"))

    def cambiarVent(self, nombre_Vent):
        self.nombre_Vent = QtWidgets.QMainWindow()
        self.ui = nombre_Vent()
        self.ui.setupUi(self.nombre_Vent)
        self.nombre_Vent.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_VentAdminUsuario()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

