# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaMenuClinica.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from VentanaMenuEspecialista import VentanaEspecialistaMenu
from VentanaMenuControles import Ui_VentanaMenuControles
from VentanaMenuUrgencias import Ui_VentanaMenuUrgencias
from VentanaMenuQuirofano import Ui_VentanaMenuQuirofano

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 424)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.botonUrgencias = QtWidgets.QPushButton(self.centralwidget)
        self.botonUrgencias.setGeometry(QtCore.QRect(140, 120, 91, 61))
        self.botonUrgencias.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.botonUrgencias.setObjectName("botonUrgencias")
        self.botonRutinario = QtWidgets.QPushButton(self.centralwidget)
        self.botonRutinario.setGeometry(QtCore.QRect(350, 120, 91, 61))
        self.botonRutinario.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.botonRutinario.setObjectName("botonRutinario")
        self.botonEspecialistas = QtWidgets.QPushButton(self.centralwidget)
        self.botonEspecialistas.setGeometry(QtCore.QRect(140, 270, 91, 61))
        self.botonEspecialistas.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.botonEspecialistas.setObjectName("botonEspecialistas")
        self.botonQuirofano = QtWidgets.QPushButton(self.centralwidget)
        self.botonQuirofano.setGeometry(QtCore.QRect(350, 270, 91, 61))
        self.botonQuirofano.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.botonQuirofano.setObjectName("botonQuirofano")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 30, 141, 41))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 30, 161, 51))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 591, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.botonEspecialistas.clicked.connect(self.abrirVentEspecialista)
        self.botonRutinario.clicked.connect(self.abrirVentControl)
        self.botonUrgencias.clicked.connect(self.abrirVentUrgencias)
        self.botonQuirofano.clicked.connect(self.abrirVentQuirofano)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botonUrgencias.setText(_translate("MainWindow", "Urgencias"))
        self.botonRutinario.setText(_translate("MainWindow", "Control Rutinario"))
        self.botonEspecialistas.setText(_translate("MainWindow", "Especialistas"))
        self.botonQuirofano.setText(_translate("MainWindow", "Quirofano"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Clinica</span></p></body></html>"))

    def abrirVentEspecialista(self):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = VentanaEspecialistaMenu()
        self.ui.setupUi(self.ventana)
        self.ventana.show()
    
    def abrirVentControl(self):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = Ui_VentanaMenuControles()
        self.ui.setupUi(self.ventana)
        self.ventana.show()
  
    
    def abrirVentUrgencias(self):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = Ui_VentanaMenuUrgencias()
        self.ui.setupUi(self.ventana)
        self.ventana.show()

    def abrirVentQuirofano(self):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = Ui_VentanaMenuQuirofano()
        self.ui.setupUi(self.ventana)
        self.ventana.show()