# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verHorasControles.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5 import QtGui, uic
import csv

class Ui_horasControles(object):
    def setupUi(self, horasControles):
        horasControles.setObjectName("horasControles")
        horasControles.resize(574, 455)
        self.centralwidget = QtWidgets.QWidget(horasControles)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(160, 20, 381, 361))
        self.listView.setObjectName("listView")
        self.botonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.botonAtras.setGeometry(QtCore.QRect(30, 370, 75, 23))
        self.botonAtras.setObjectName("botonAtras")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 101, 71))
        self.label.setObjectName("label")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(20, 100, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.botonBuscar = QtWidgets.QPushButton(self.centralwidget)
        self.botonBuscar.setGeometry(QtCore.QRect(40, 140, 75, 23))
        self.botonBuscar.setObjectName("botonBuscar")
        horasControles.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(horasControles)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 574, 21))
        self.menubar.setObjectName("menubar")
        horasControles.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(horasControles)
        self.statusbar.setObjectName("statusbar")
        horasControles.setStatusBar(self.statusbar)
        self.botonBuscar.clicked.connect(self.buscar_datos)
        self.modelo = QtGui.QStandardItemModel()
        self.listView.setModel(self.modelo)
        fecha_actual = QDate.currentDate()
        self.dateEdit.setMinimumDate(fecha_actual)

        self.retranslateUi(horasControles)
        QtCore.QMetaObject.connectSlotsByName(horasControles)

    def retranslateUi(self, horasControles):
        _translate = QtCore.QCoreApplication.translate
        horasControles.setWindowTitle(_translate("horasControles", "MainWindow"))
        self.botonAtras.setText(_translate("horasControles", "Atras"))
        self.label.setText(_translate("horasControles", "<html><head/><body><p><span style=\" font-size:14pt;\">Busqueda </span></p><p><span style=\" font-size:14pt;\">por fecha</span></p></body></html>"))
        self.botonBuscar.setText(_translate("horasControles", "Buscar"))

    def buscar_datos(self):
        fecha_ingresada = self.dateEdit.date().toString("yyyy-MM-dd")

        try:
            datos_encontrados = self.buscar_por_fecha('Control.csv', fecha_ingresada)

            self.modelo.clear()

            if datos_encontrados:
                for fila in datos_encontrados:
                    nombre = fila[1]
                    hora = fila[2]
                    sala = fila[3]
                    datos_completos = f"Nombre paciente: {nombre}, Hora: {hora}, Sala: {sala}"
                    item = QtGui.QStandardItem(datos_completos)
                    self.modelo.appendRow(item)
            else:
                item = QtGui.QStandardItem("No se encontraron registros con la fecha ingresada.")
                self.modelo.appendRow(item)
        except FileNotFoundError:
            item = QtGui.QStandardItem("El archivo CSV no fue encontrado.")
            self.modelo.appendRow(item)
    
    def buscar_por_fecha(self, archivo_csv, fecha):
        datos_encontrados = []
        with open(archivo_csv, 'r') as archivo:
            lector_csv = csv.reader(archivo)
            next(lector_csv)  # Ignorar la primera fila (encabezados)
            for fila in lector_csv:
                fecha_actual = fila[0]
                if fecha_actual == fecha:
                    datos_encontrados.append(fila)
        return datos_encontrados