# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verUrgencias.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_horasUrgencias(object):
    def setupUi(self, horasUrgencias):
        horasUrgencias.setObjectName("horasUrgencias")
        horasUrgencias.resize(574, 455)
        self.centralwidget = QtWidgets.QWidget(horasUrgencias)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(160, 20, 381, 361))
        self.listView.setObjectName("listView")
        self.botonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.botonAtras.setGeometry(QtCore.QRect(30, 370, 75, 23))
        self.botonAtras.setObjectName("botonAtras")
        self.botonAtras.clicked.connect(horasUrgencias.close)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 101, 71))
        self.label.setObjectName("label")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(20, 100, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.botonBuscar = QtWidgets.QPushButton(self.centralwidget)
        self.botonBuscar.setGeometry(QtCore.QRect(40, 140, 75, 23))
        self.botonBuscar.setObjectName("botonBuscar")
        horasUrgencias.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(horasUrgencias)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 574, 21))
        self.menubar.setObjectName("menubar")
        horasUrgencias.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(horasUrgencias)
        self.statusbar.setObjectName("statusbar")
        horasUrgencias.setStatusBar(self.statusbar)

        self.retranslateUi(horasUrgencias)
        QtCore.QMetaObject.connectSlotsByName(horasUrgencias)

    def retranslateUi(self, horasUrgencias):
        _translate = QtCore.QCoreApplication.translate
        horasUrgencias.setWindowTitle(_translate("horasUrgencias", "MainWindow"))
        self.botonAtras.setText(_translate("horasUrgencias", "Atras"))
        self.label.setText(_translate("horasUrgencias", "<html><head/><body><p><span style=\" font-size:14pt;\">Busqueda </span></p><p><span style=\" font-size:14pt;\">por fecha</span></p></body></html>"))
        self.botonBuscar.setText(_translate("horasUrgencias", "Buscar"))
    
    
